sonar.projectKey=anm0200_simulador-aerolinea
sonar.organization=anm0200
sonar.projectName=simulador-aerolinea

# 1. Declaramos que es un proyecto con múltiples módulos
sonar.modules=frontend,backend

# 2. Configuración específica del Frontend
frontend.sonar.sources=src
frontend.sonar.exclusions=**/node_modules/**,**/dist/**,**/.angular/**,**/*.spec.ts,**/*.test.ts,src/main.ts,src/server.ts,src/main.server.ts,src/app/app.config*.ts,src/app/app.routes*.ts,src/app/features/**/pages/**,src/app/features/**/components/**,src/app/shared/components/**,src/test-setup.ts
frontend.sonar.coverage.exclusions=src/app/features/methods/services/graph.service.ts,src/app/core/services/flight.service.ts
frontend.sonar.javascript.lcov.reportPaths=coverage/lcov.info

# 3. Configuración específica del Backend
backend.sonar.sources=src
backend.sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts,**/*.test.ts,prisma/**,src/index.ts
backend.sonar.coverage.exclusions=src/scripts/reset-users.ts
backend.sonar.javascript.lcov.reportPaths=coverage/lcov.info