sonar.projectKey=anm0200_simulador-aerolinea
sonar.organization=anm0200
sonar.projectName=simulador-aerolinea
sonar.sources=frontend/src,backend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/.angular/**,**/database/**,**/*.spec.ts,**/*.test.ts,backend/prisma/**
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info